In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

import joblib

In [2]:
df = pd.read_csv("../data/cleaned_data.csv")

df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [3]:
print(df.shape)

df.info()

(1200, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   object
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   object
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   object
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
dtypes: float64(5), int64(5), object(3)
memory usage: 122.0+ KB

In [4]:
X = df.drop("depression_label", axis=1)

y = df["depression_label"]

print("Feature Shape :", X.shape)

print("Target Shape :", y.shape)

Feature Shape : (1200, 12)
Target Shape : (1200,)

In [5]:
print(y.value_counts())

print("\nPercentage\n")

print(y.value_counts(normalize=True) * 100)

depression_label
0    1169
1      31
Name: count, dtype: int64

Percentage

depression_label
0    97.416667
1     2.583333
Name: proportion, dtype: float64

In [6]:
categorical_features = X.select_dtypes(include="object").columns.tolist()

numerical_features = X.select_dtypes(exclude="object").columns.tolist()

print("Categorical Features")

print(categorical_features)

print("\nNumerical Features")

print(numerical_features)

Categorical Features
['gender', 'platform_usage', 'social_interaction_level']

Numerical Features
['age', 'daily_social_media_hours', 'sleep_hours', 'screen_time_before_sleep', 'academic_performance', 'physical_activity', 'stress_level', 'anxiety_level', 'addiction_level']

In [7]:
numeric_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['age', 'daily_social_media_hours',
                                  'sleep_hours', 'screen_time_before_sleep',
                                  'academic_performance', 'physical_activity',
                                  'stress_level', 'anxiety_level',
                                  'addiction_level']),
                                ('cat',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'platform_usage',
                                  'social_interaction_level'])])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Set :", X_train.shape)

print("Testing Set :", X_test.shape)

Training Set : (960, 12)
Testing Set : (240, 12)

In [9]:
preprocessor.fit(X_train)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['age', 'daily_social_media_hours',
                                  'sleep_hours', 'screen_time_before_sleep',
                                  'academic_performance', 'physical_activity',
                                  'stress_level', 'anxiety_level',
                                  'addiction_level']),
                                ('cat',
                                 Pipeline(steps=[('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'platform_usage',
                                  'social_interaction_level'])])

In [10]:
X_train_processed = preprocessor.transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print(X_train_processed.shape)

print(X_test_processed.shape)

(960, 17)
(240, 17)

In [11]:
feature_names = preprocessor.get_feature_names_out()

print(feature_names)

['num__age' 'num__daily_social_media_hours' 'num__sleep_hours'
 'num__screen_time_before_sleep' 'num__academic_performance'
 'num__physical_activity' 'num__stress_level' 'num__anxiety_level'
 'num__addiction_level' 'cat__gender_female' 'cat__gender_male'
 'cat__platform_usage_Both' 'cat__platform_usage_Instagram'
 'cat__platform_usage_TikTok' 'cat__social_interaction_level_high'
 'cat__social_interaction_level_low'
 'cat__social_interaction_level_medium']

In [12]:
X_train_df = pd.DataFrame(
    X_train_processed,
    columns=feature_names
)

X_test_df = pd.DataFrame(
    X_test_processed,
    columns=feature_names
)

X_train_df.head()

,num__age,num__daily_social_media_hours,num__sleep_hours,num__screen_time_before_sleep,num__academic_performance,num__physical_activity,num__stress_level,num__anxiety_level,num__addiction_level,cat__gender_female,cat__gender_male,cat__platform_usage_Both,cat__platform_usage_Instagram,cat__platform_usage_TikTok,cat__social_interaction_level_high,cat__social_interaction_level_low,cat__social_interaction_level_medium
0,-1.440460,-1.156923,-0.442800,0.349862,1.105081,1.513064,-0.498161,-0.576967,1.578744,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,-1.440460,1.625061,-0.306159,1.328660,-0.252965,-1.233086,1.235829,1.514492,-0.917529,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.043276,0.307279,1.128562,0.489690,-0.566360,1.169796,1.235829,1.514492,1.578744,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,1.527011,-0.620049,-0.989360,0.489690,-1.663244,-0.203279,-1.538554,1.514492,1.222133,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.537854,0.209666,-1.057680,0.489690,-1.715477,-0.031645,1.235829,-0.576967,1.222133,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [13]:
train_df = X_train_df.copy()

train_df["depression_label"] = y_train.reset_index(drop=True)

test_df = X_test_df.copy()

test_df["depression_label"] = y_test.reset_index(drop=True)

train_df.to_csv("../data/train_processed.csv", index=False)

test_df.to_csv("../data/test_processed.csv", index=False)

print("Processed datasets saved successfully!")

Processed datasets saved successfully!

In [14]:
joblib.dump(preprocessor, "../models/preprocessor.pkl")

print("Preprocessor saved successfully!")

Preprocessor saved successfully!